import type { Metadata } from "next";
import { Red_Hat_Display, Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider/provider";

const celliad = localFont({
  src: "../fonts/Celliad.woff",
  weight: "100 900",
  variable: "--font-celliad",
});

const excali = localFont({
  src: "../fonts/Virgil.woff2",
  weight: "100 900",
  variable: "--font-excali",
});

const redhat = Red_Hat_Display({
  variable: "--font-redhat",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${redhat.variable} ${poppins.variable} ${excali.variable} ${celliad.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
